"""added age

Revision ID: 2b1fe3719b43
Revises: a5e78b758524
Create Date: 2019-11-27 13:29:05.163218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b1fe3719b43'
down_revision = 'a5e78b758524'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cat', sa.Column('age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cat', 'age')
    # ### end Alembic commands ###
