"""make sure its up to date

Revision ID: 9cd54e870ab1
Revises: a987b15efac0
Create Date: 2019-11-27 13:44:00.767324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cd54e870ab1'
down_revision = 'a987b15efac0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cat', 'age2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cat', sa.Column('age2', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
