"""new db

Revision ID: a987b15efac0
Revises: 2b1fe3719b43
Create Date: 2019-11-27 13:35:33.909094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a987b15efac0'
down_revision = '2b1fe3719b43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
