"""First revision

Revision ID: 221a8739a871
Revises: 
Create Date: 2022-03-19 08:46:41.394939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '221a8739a871'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cat', sa.Column('weight', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cat', 'weight')
    # ### end Alembic commands ###
