"""First revision redo

Revision ID: 7255290947e5
Revises: 221a8739a871
Create Date: 2022-03-19 10:45:15.143957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7255290947e5'
down_revision = '221a8739a871'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
